name: velocitygpt
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - ipython
  - ipywidgets
  - jupyter
  - jupyter-resource-usage
  - jupyter_server[version='<2.0.0']
  - matplotlib
  - notebook[version='>=6.0.0,<7.0.0']
  - pandas
  - pip
  - python=3.8
  - pytorch::pytorch==1.12.1
  - pytorch::torchaudio==0.12.1
  - pytorch::torchvision==0.13.1
  - scikit-fmm
  - scikit-image
  - scipy
  - tokenizers=0.11.4
  - tqdm
  - transformers=4.20.1
  - natsort
  - pylops
  - graphviz
  - python-graphviz
  - wandb
  - onnx
  - scikit-learn
  - pytorch-lightning
  - pip:
    - pynvml
    - pytorch-msssim
    - pytorch-warmup